---
- hosts: master
  become: yes
  tasks:
    - name: remove swap
      shell: "swapoff -a"

    - name: initialize the cluster
      shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all

    - name: create .kube directory
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: chown $HOME/.kube/config
      become_user: kube
      shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: install Pod network
      become_user: kube
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
