---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure vim, curl and neofetch are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - neofetch